### ISSUE TITLE
Validator - When paginating being able to pick out specific fields for searching

### ISSUE THREAD

**Issue by yemijaiyeola** [WeAreSnook/human-services#5]
When paginating being able to pick out specific fields for searching to validate interoperability?

**Comment by yemijaiyeola** [comment]
Level 1 - Paginatable and can access a detail view for the service - small amount of work required here
Level 2 - Supporting other parameters included in the standard - more advanced features such as taxonomies
e.g postcode, search for a postcode do we find a service registered at that postcode

**Comment by yemijaiyeola** [comment]
Styling required for the output here as well.

**Comment by esd-org-uk** [comment]
We will ignore the following parameters as there seems to be #9 some discussion due on taxonomy.

- circumstance
- taxonomy_id
- taxonomy_type
- vocabulary
- service_type

**Comment by PorismDominicSkinner** [comment]
This is now done. When running the http://servicevalidator.esd.org.uk/ it parses all of the services and picks out information from the services in order to perform the search.

It tests:

- Taxonomy - testing _taxonomy_id_  and _vocabulary_ parameters. I know this is mentioned above but doesn't make sense not to do it as it is based on taxonomies in the data so this can be then fed back into the API to see if it works or not.
- Keyword - testing the _text_ parameters. It gets a service title and passes it back to the API to see if the matching service is returned in the results.
- Min and Max age - testing _minimum_age_ and _maximum_age_ parameters. It gets the min and maximum ages if present and then does a search to see if it can find the matching services. Services with the most matching matching parameters are tested if possible so were there is a minimum and maximum age present.
- Postcode - testing proximity and postcode parameters. It finds a service postcode then sees if it can find the same service within a 100 meter proximity.
- Regular Schedule - _day_, _start_time_ and _end_time_ parameters. It gets all of the days, start_time and end_time values and checks that it falls within the valid to and from time frame before continuing. Services with the most matching matching parameters are tested if possible so were there is a days and start and end times present for the regular scheule.

To pass level 2 it must have found at least one level two test that can be used. All level two tests are passed and level one was passed.
